[build]
  base = "frontend" #  Set the base directory if your frontend is in a subfolder
  command = "npm run build"
  publish = "frontend/dist"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200